# Generated by Django 3.1.3 on 2021-01-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Пример: "/about/contact/". Убедитесь, что ввели начальную и конечную косые черы.', unique=True, verbose_name='URL - Путь')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключевые слова')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'META-тег',
                'verbose_name_plural': 'META-теги',
            },
        ),
    ]
