# Generated by Django 3.1.3 on 2021-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210207_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
