# Generated by Django 3.1.3 on 2020-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201117_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='В заказе'),
        ),
    ]
